#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
hostname: #@ "harbor.{}".format(data.values.local.domain)
harborAdminPassword: admin
secretKey: abcdefghijklmnop
core:
  secret: opensesame
  xsrfKey: abcdefghijklmnopqrstuvwxyzabcdef
database:
  password: databasepassword
jobservice:
  secret: jobservicesecret
registry:
  secret: registrysecret
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name": "harbor-pkg-values"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
