#@ load("@ytt:data", "data")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: bootiful.local.community.tanzu.vmware.com.1.0.0
spec:
  refName: bootiful.local.community.tanzu.vmware.com
  version: 1.0.0
  releasedAt: #@ data.values.build.date
  valuesSchema:
    openAPIv3:
      title: Values schema
      examples:
        - local.domain: 127.0.0.1.nip.io
      properties:
        local.domain:
          type: string
          description: Base domain for cluster
          default: 127.0.0.1.nip.io
          examples:
            - nuc.dashaun.org
            - mbp.dashaun.dev
            - tce.dashaun.io
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: #@ data.values.pkg.bootiful
      template:
      - ytt:
          paths:
          - config/
      - kbld:
          paths:
          - '-'
          - .imgpkg/images.yml
      deploy:
      - kapp: {}
