#@ load("@ytt:data", "data")
---
apiVersion: data.packaging.carvel.dev/v1alpha1
kind: PackageMetadata
metadata:
  name: registry.local.community.tanzu.vmware.com
spec:
  displayName: local-registry
  longDescription: Harbor for TCE Local
  shortDescription: Harbor for TCE Local
  providerName: TCE Local
  maintainers:
  - name: Alexandre Roman
  - name: DaShaun Carter
  supportDescription: #@ "Go to {} for documentation".format(data.values.source.url)
