#@ load("@ytt:overlay", "overlay")
#@ load("@ytt:data", "data")
#@ load("@ytt:yaml", "yaml")

#@ def config():
kp_default_repository: #@ "harbor.{}".format(data.values.local.domain)
kp_default_repository_username: admin
kp_default_repository_password: admin
#@ end

#@overlay/match by=overlay.subset({"metadata":{"name": "kpack-pkg-values"}})
---
stringData:
  values.yml: #@ yaml.encode(config())
