apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: cert-manager
spec:
  packageRef:
    refName: cert-manager.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.6.1"
  serviceAccountName: local-paved-default-sa
